[profile.default]
solc = "0.8.17"
src = "src"
out = "out"
libs = ["lib"]

[fmt]
line_length = 79
tab_width = 2
number_underscore = "thousands"
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
